name: test mssql
on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  test-mssql-collation:
    name: test mssql with collation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: test mssql with collation
        env:
          TEST_MSSQL_HOST: mssql2
          TEST_MSSQL_DBNAME: xorm_test
          TEST_MSSQL_USERNAME: sa
          TEST_MSSQL_PASSWORD: "yourStrong(!)Password"
          TEST_MSSQL_COLLATION: SQL_Latin1_General_CP1_CS_AS
        run: TEST_MSSQL_DEFAULT_VARCHAR=NVARCHAR TEST_MSSQL_DEFAULT_CHAR=NCHAR make test-mssql

    services:
      mssql2:
        image: mcr.microsoft.com/mssql/server:latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: yourStrong(!)Password
          MSSQL_PID: Standard