name: test mssql
on: 
  push:
    branches:
      - main
      - v1
  pull_request:

jobs:
  test-mssql:
    name: test mssql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: test mssql
        env:
          TEST_MSSQL_HOST: mssql
          TEST_MSSQL_DBNAME: xorm_test
          TEST_MSSQL_USERNAME: sa
          TEST_MSSQL_PASSWORD: "yourStrong(!)Password"
        run: TEST_MSSQL_DEFAULT_VARCHAR=NVARCHAR TEST_MSSQL_DEFAULT_CHAR=NCHAR make test-mssql

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: yourStrong(!)Password
          MSSQL_PID: Standard